// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZCtDZOtte4eWvyL5fT0z9PqdRQqDbnu4',
    appId: '1:169104788079:web:cb174ee9ae86d79eb79b9a',
    messagingSenderId: '169104788079',
    projectId: 'fasum-app-adec0',
    authDomain: 'fasum-app-adec0.firebaseapp.com',
    storageBucket: 'fasum-app-adec0.firebasestorage.app',
    measurementId: 'G-Z92S0JDHB7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDqePa3rXjIhNG1pVAuftf2w7ae9E8F3LY',
    appId: '1:169104788079:android:b98397eb5a9eb335b79b9a',
    messagingSenderId: '169104788079',
    projectId: 'fasum-app-adec0',
    storageBucket: 'fasum-app-adec0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCYvRD1lEXl8ISSO4g4jyVz-syd-rhFvbY',
    appId: '1:169104788079:ios:581c76a2062e6cd2b79b9a',
    messagingSenderId: '169104788079',
    projectId: 'fasum-app-adec0',
    storageBucket: 'fasum-app-adec0.firebasestorage.app',
    iosBundleId: 'com.example.fasumApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCYvRD1lEXl8ISSO4g4jyVz-syd-rhFvbY',
    appId: '1:169104788079:ios:581c76a2062e6cd2b79b9a',
    messagingSenderId: '169104788079',
    projectId: 'fasum-app-adec0',
    storageBucket: 'fasum-app-adec0.firebasestorage.app',
    iosBundleId: 'com.example.fasumApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDZCtDZOtte4eWvyL5fT0z9PqdRQqDbnu4',
    appId: '1:169104788079:web:aa7b722809f5a4c9b79b9a',
    messagingSenderId: '169104788079',
    projectId: 'fasum-app-adec0',
    authDomain: 'fasum-app-adec0.firebaseapp.com',
    storageBucket: 'fasum-app-adec0.firebasestorage.app',
    measurementId: 'G-81ZVLN4M8H',
  );
}
